# 服务配置文件模板
spring:
  profiles: prod
  application:
    name: job
    desc: Job Service
    version: 4.0.0
    packageName: com.tencent.bk.codecc.job
  # consul config do not need to change
  redis:
    database: 1
    host: __REDIS_IP__
    port:
    password: __REDIS_PASS__
    pool:
      maxActive: 16
      maxWait: -1
      maxIdle: 16
      minIdle: 0
  rabbitmq:
    virtual-host: __RABBITMQ_CODECC_VHOST__
    username: __RABBITMQ_USERNAME__
    password: __RABBITMQ_PASSWORD__
    addresses: __RABBITMQ_HOST__:__RABBITMQ__PORT__
    listener:
      simple:
        concurrency: 10
        acknowledge-mode: auto
  cloud:
    consul:
      discovery:
        tags: __DEVOPS_CONSUL_TAG__
        health-check-path: /management/health
        heartbeat:
          enabled: true
        query-passing: true
        preferIpAddress: true
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  data:
    mongodb:
      uri: mongodb://__MONGODB_USER__:__MONGODB_PASS__@__MONGODB_IP__:__MONGODB_PORT__/db_defect

server:
  port:
  servlet-path: /
  undertow:
    worker-threads: 100

# monitor path config
management:
  security:
    enabled: false
  context-path: /management


auth:
  envName: prod
  url: __CODECC_AUTH_URL__
  codeccCode: __APP_CODE__
  codeccSecret: __APP_TOKEN__
  systemId: __CODECC_SYSTEM_ID__
  codeccResourceType: __CODECC_RESOURCE_TYPE__
  pipelineResourceType: __PIPELINE_RESOURCE_TYPE__
  codeccServiceCode: __CODECC_SERVICE_CODE__
  pipelineServiceCode: __PIPELINE_SERVICE_CODE__

bkAuth:
  envName: prod
  url: __CODECC_BK_AUTH_URL__
  codeccCode: __APP_CODE__
  codeccSecret: __APP_TOKEN__
  systemId: __CODECC_SYSTEM_ID__
  codeccResourceType: __CODECC_RESOURCE_TYPE__
  pipelineResourceType: __PIPELINE_RESOURCE_TYPE__
  codeccServiceCode: __CODECC_SERVICE_CODE__
  pipelineServiceCode: __PIPELINE_SERVICE_CODE__

devopsGateway:
  host: __DEVOPS_GATEWAY_HOST__


codecc:
  encryptor:
    password: __CODECC_ENCRYPTOR_PASS__
  env: internal
  privatetoken: __CODECC_PRIVATE_TOKEN__
  classurl: __CODECC_CLASS_URL__:__CODECC_CLASS_PORT__/downloadFile?fileName=
  public:
    account: __CODECC_PUBLIC_ACCOUNT__
    password: __CODECC_PUBLIC_PASS__