spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: environment${service-suffix}
    desc: DevOps Environment Service
    version: 4.0
    packageName: com.tencent.devops.environment

server:
  port: 21919
