steps:
  - taskType: bash@latest
    displayName: bash
    inputs:
      scriptType: SHELL
      content: |
        #!/bin/bash
        echo "hello world"
  - taskType: codeCCScan@latest
    displayName: codecc检查
    inputs:
      languages:
        - JS
      tools:
        - ESLINT
      script: echo 123
      toolScanType: 0
      languageRuleSetMap:
        JS_RULE:
          - standard_js_preferable
          - standard_js