spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: misc${service-suffix}
    desc: Devops Misc Service
    version: 4.0
    packageName: com.tencent.devops.misc


server:
  port: 21926
