# 服务配置文件模板
spring:
  application:
    name: schedule
    desc: Schedule Service
    version: 4.0.0
    packageName: com.tencent.bk.codecc.schedule
  data:
    mongodb:
#      uri: mongodb://codecc_ee:codecc1024@10.125.224.233:27017,10.125.224.233:27018,10.125.224.233:27019/db_schedule?replicaSet=rs0&slaveOk=true
#      uri: mongodb://codecc_ee:codecc1024@9.134.78.250:27017/db_schedule
#      uri: mongodb://codecc_ee:codecc1024@9.134.77.247:27017/db_schedule
#      uri: mongodb://codecc_ee:codecc1024@9.134.77.145:27017/db_schedule
#      uri: mongodb://codecc_ee:codecc1024@9.134.92.80:27017/db_schedule?maxPoolSize=200
  redis:
#    host: 9.134.35.250
#    password: MQKfk)2549Sx
#    host: 9.134.35.236
#    password: dmect(3675Sd
    host: 9.134.34.137
    password: AfMHU!2578Sj
    port: 6379
    pool:
      maxActive: 16
      maxWait: -1
      maxIdle: 16
      minIdle: 0
#  rabbitmq:
#    virtual-host: codecc_test
#    username: codecc_test
#    password: codecc_10241024
#    addresses: 9.134.78.69:5672
#    listener:
#      simple:
#        concurrency: 10
#        acknowledge-mode: auto
  cloud:
    consul:
      discovery:
        tags: dev
        health-check-path: /management/health
        heartbeat:
          enabled: true
        query-passing: true
        preferIpAddress: true
  #      port: 8080
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
# 服务器端口配置，在同一台机器上部署多个微服务，端口号要不同 23910
server:
  port: 8088 # 服务端口

result:
  log:
    path: /data/bkee/codecc/cfs/result_log # 日志文件目录
#
#---
#
#spring:
#  profiles: test
#  redis:
#    host: 9.134.35.236
#    password: dmect(3675Sd
#    port: 6379
#    pool:
#      maxActive: 16
#      maxWait: -1
#      maxIdle: 16
#      minIdle: 0
#  rabbitmq:
#    virtual-host: codecc
#    username: codecc_test
#    password: codecc_10241024
#    addresses: 9.134.78.69:5672
#    listener:
#      simple:
#        concurrency: 10
#        acknowledge-mode: auto
#  cloud:
#    consul:
#      discovery:
#        tags: test
#        health-check-path: /management/health
#        heartbeat:
#          enabled: true
#        query-passing: true
#        preferIpAddress: true
#    #      port: 8080
#    http:
#      encoding:
#        charset: UTF-8
#        enabled: true
#        force: true
#  # 服务器端口配置，在同一台机器上部署多个微服务，端口号要不同 23910
#  server:
#    port: 8088 # 服务端口
