spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: repository${service-suffix}
    desc: DevOps Repository Service
    version: 4.0.0
    packageName: com.tencent.devops.repository

server:
  port: 21931
