# 服务配置文件模板
spring:
  application:
    name: defect
    desc: Defect Service
    version: 4.0.0
    packageName: com.tencent.bk.codecc.defect
  data:
    mongodb:
      #uri: mongodb://codecc_ee:codecc1024@9.134.78.250:27017/db_defect
      uri: mongodb://codecc_ee:codecc1024@9.134.77.247:27017/db_defect?maxPoolSize=200
#      uri: mongodb://codecc_ee:codecc1024@9.134.77.145:27017/db_defect?maxPoolSize=200
  # consul config do not need to change
  redis:
#    host: 9.134.35.250
#    password: MQKfk)2549Sx
    host: 9.134.35.236
    password: dmect(3675Sd
    port: 6379
    pool:
      maxActive: 16
      maxWait: -1
      maxIdle: 16
      minIdle: 0
  rabbitmq:
    virtual-host: codecc_test
    username: codecc_test
    password: codecc_10241024
    addresses: 9.134.78.69:5672
    listener:
      simple:
        concurrency: 10
        acknowledge-mode: auto
  cloud:
    consul:
#      host: 9.134.77.223
#      port: 8500
      discovery:
        tags: dev
        health-check-path: /management/health
        heartbeat:
          enabled: true
        query-passing: true
        preferIpAddress: true
  #      port: 8080
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# 服务器端口配置，在同一台机器上部署多个微服务，端口号要不同 23910
server:
  port: 8082 # 服务端口


time:
  analysis:
    maxhour: 7

devops:
  retry:
    attempt: 7
    interval: 1000

codecc:
  dockernizedTools: 1
  gateway:
    host: localhost